In [139]:
pip install --upgrade protobuf

Note: you may need to restart the kernel to use updated packages.


In [140]:
import numpy as np
import tensorflow as tf

In [141]:
with open("MLprojects.txt", "r", encoding='utf-8') as file:
    mlprojects_details = file.read()

In [142]:
mlprojects_details

"Machine Learning Projects for Beginners \nThese beginner machine learning projects consist of dealing with structured, tabular data. You will apply the skills of data cleaning, processing, and visualization for analytical purposes and use the scikit-learn framework to train and validate machine learning models. \n\nIf you want to learn the basic concepts of machine learning first, we have a no-code understanding machine learning course. You can also check out some of our AI projects if you're looking to improve your skills in that area. \n\n1. Predict energy consumption\nIn the Predict Energy Consumption project, you will use regression and machine learning models to predict daily power consumption based on temporal factors like time of day and temperature. The goal is to uncover patterns that can optimize energy usage, improving efficiency and reducing costs. This is particularly important for utilities and businesses aiming to reduce operational expenses, promote energy conservation

In [143]:
tokenizer = tf.keras.preprocessing.text.Tokenizer()

In [144]:
tokenizer.fit_on_texts([mlprojects_details])

In [145]:
tokenizer.get_config()

{'num_words': None,
 'filters': '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
 'lower': True,
 'split': ' ',
 'char_level': False,
 'oov_token': None,
 'document_count': 1,
 'word_counts': '{"machine": 8, "learning": 8, "projects": 3, "for": 6, "beginners": 1, "these": 1, "beginner": 1, "consist": 1, "of": 10, "dealing": 2, "with": 4, "structured": 1, "tabular": 1, "data": 8, "you": 17, "will": 8, "apply": 2, "the": 21, "skills": 3, "cleaning": 1, "processing": 2, "and": 20, "visualization": 1, "analytical": 1, "purposes": 1, "use": 4, "scikit": 2, "learn": 3, "framework": 1, "to": 15, "train": 2, "validate": 1, "models": 4, "if": 2, "want": 1, "basic": 1, "concepts": 1, "first": 1, "we": 1, "have": 1, "a": 21, "no": 1, "code": 2, "understanding": 1, "course": 1, "can": 9, "also": 1, "check": 1, "out": 1, "some": 1, "our": 1, "ai": 1, "you\'re": 1, "looking": 1, "improve": 2, "your": 3, "in": 9, "that": 3, "area": 1, "1": 2, "predict": 8, "energy": 5, "consumption": 4, "project": 12, "regres

In [146]:
tokenizer.word_index

{'the': 1,
 'a': 2,
 'and': 3,
 'you': 4,
 'to': 5,
 'project': 6,
 'of': 7,
 'can': 8,
 'in': 9,
 'machine': 10,
 'learning': 11,
 'data': 12,
 'will': 13,
 'predict': 14,
 'on': 15,
 'is': 16,
 'for': 17,
 'as': 18,
 'energy': 19,
 'dataset': 20,
 'such': 21,
 'insurance': 22,
 'wine': 23,
 'with': 24,
 'use': 25,
 'models': 26,
 'consumption': 27,
 'this': 28,
 'charges': 29,
 'predicting': 30,
 'build': 31,
 'credit': 32,
 'card': 33,
 'using': 34,
 'quality': 35,
 'projects': 36,
 'skills': 37,
 'learn': 38,
 'your': 39,
 'that': 40,
 'regression': 41,
 'guided': 42,
 'replicate': 43,
 'different': 44,
 'predictive': 45,
 'it': 46,
 'approvals': 47,
 'automatic': 48,
 'feature': 49,
 'dealing': 50,
 'apply': 51,
 'processing': 52,
 'scikit': 53,
 'train': 54,
 'if': 55,
 'code': 56,
 'improve': 57,
 '1': 58,
 'based': 59,
 'factors': 60,
 'like': 61,
 'important': 62,
 'manage': 63,
 'more': 64,
 'demand': 65,
 'working': 66,
 'from': 67,
 'health': 68,
 'attributes': 69,
 'applic

In [147]:
input_sequences = []
for sentence in mlprojects_details.split('\n'):
    token_list = tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1, len(token_list)):
        sequence = token_list[:i+1]
        input_sequences.append(sequence)

In [148]:
input_sequences[:5]

[[10, 11], [10, 11, 36], [10, 11, 36, 17], [10, 11, 36, 17, 89], [90, 91]]

In [149]:
# to find the what is the maximum length of sequence here
max_length = max([len(input_sequence) for input_sequence in input_sequences])
max_length

74

In [150]:
# Now add the padding to other sequences with match to the maximum length
input_sequences = np.array(tf.keras.preprocessing.sequence.pad_sequences(input_sequences, maxlen=max_length, padding='pre'))

In [151]:
input_sequences[0]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0, 10, 11])

In [152]:
x = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [153]:
x[0]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0, 10])

In [154]:
y

array([ 11,  36,  17,  89,  91,  10,  11,  36,  92,   7,  50,  24,  93,
        94,  12,   4,  13,  51,   1,  37,   7,  12,  95,  52,   3,  96,
        17,  97,  98,   3,  25,   1,  53,  38,  99,   5,  54,   3, 100,
        10,  11,  26,   4, 101,   5,  38,   1, 102, 103,   7,  10,  11,
       104, 105, 106,   2, 107,  56, 108,  10,  11, 109,   4,   8, 110,
       111, 112, 113,   7, 114, 115,  36,  55, 116, 117,   5,  57,  39,
        37,   9,  40, 118,  14,  19,  27,   1,  14,  19,  27,   6,   4,
        13,  25,  41,   3,  10,  11,  26,   5,  14, 119, 120,  27,  59,
        15, 121,  60,  61, 122,   7, 123,   3, 124,   1, 125,  16,   5,
       126, 127,  40,   8, 128,  19, 129, 130, 131,   3, 132, 133,  28,
        16, 134,  62,  17, 135,   3, 136, 137,   5, 138, 139, 140, 141,
        19, 142,   3, 143,  63, 144, 145,   9,   2,  64, 146, 147,  14,
        19,  27,   6,  16,   2,  42,   6, 148,   4,   8,  43,   1, 149,
        15,   2,  44,  20,  21,  18, 150, 151, 152,  65,  66,  1

In [155]:
num_classes = len(tokenizer.word_index) + 1
num_classes

265

In [156]:
# one hot encoding for all y values
y = np.array(tf.keras.utils.to_categorical(y, num_classes = num_classes))

In [157]:
y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

# model initialization

In [159]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Embedding(num_classes, 80, input_length=max_length-1))
model.add(tf.keras.layers.LSTM(100))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

In [160]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_2 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [183]:
model.compile(loss='categorical_crossentropy',
             optimizer = 'adam',
             metrics=['accuracy'])

In [185]:
history = model.fit(x,y, epochs = 100)

Epoch 1/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.0054 - loss: 5.5669 
Epoch 2/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.0399 - loss: 5.3499
Epoch 3/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.0345 - loss: 5.1734
Epoch 4/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.0490 - loss: 5.1177
Epoch 5/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.0490 - loss: 5.0609
Epoch 6/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.0617 - loss: 5.0175
Epoch 7/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.0526 - loss: 4.9655
Epoch 8/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.0581 - loss: 4.8998
Epoch 9/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.0744 - loss: 4.8399
Epoch 10/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.0672 - loss: 4.7591
Epoch 11/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.0853 - loss: 4.6939
Epoch 12/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/ste

In [191]:
input_text = "Machine learning is"

In [193]:
token_list = tokenizer.texts_to_sequences([input_text])[0]
print(token_list)

[10, 11, 16]


In [195]:
token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen = max_length-1, padding='pre')
print(token_list)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10 11
  16]]


In [197]:
prediction = np.argmax(model.predict(token_list), axis=1)
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 305ms/step
[5]


In [205]:
for word, index in tokenizer.word_index.items():
    if index == prediction:
        print(word)

to


In [207]:
input_text = "Machine learing"
for i in range(6):
    token_list = tokenizer.texts_to_sequences([input_text])[0]
    token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen=max_length-1, padding='pre')
    prediction = np.argmax(model.predict(token_list), axis=1)
    output_word = ""
    for word, index in tokenizer.word_index.items():
        if index == prediction:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
Machine learing learning projects for beginners of dealing
